
const EconomyData = [
    {
        id:1,
        title:'Global Economic Review',
        text:'The COVID-19 outbreak that began in early 2020 has had a profound impact on the world economy. The pandemic engulfed the whole world and ravaged the health care system of many developed nations. Initially, the supply shock caused by the abrupt closing of businesses across the world transformed into an unprecedented demand shock, which had socio-economic consequences. COVID-19 pandemic triggered unprecedented restrictions not only on the movement of people but also on a range of economic and financial activities. Supply chains and industries like tourism, travelling, hotels and hospitality, transportation and education were severely impacted.',
        p1:'The human cost has been substantial, especially in developed countries despite being advanced in medical and health systems. It had exposed the lack of capacity and strained healthcare systems around the world. The health crisis has been accompanied by the deepest economic downturn since the Great Depression, which has resulted in the loss of millions of jobs, closure of businesses and tipping millions into extreme poverty. It has been a crisis like no other. The Great Lockdown decimated livelihoods world-wide and pushed low-income households into abject poverty',
        p2:'However, to address the dual crisis i.e. health and economic, countries all over the world responded swiftly with a variety of policy measures; mostly in the form of monetary and fiscal interventions for the economy and health measures for the pandemic. The objective was to salvage the economies from potential welfare loss by compensating unemployed masses as well as businesses with the provision of necessary assistance. Since the economic activity was at a standstill, these interventions helped economies in managing the supply lines intact. On the monetary side, the central banks adopted expansionary policy stances, quickly provided liquidity support and supported credit extension to a wide array of borrowers. Simultaneously, on the fiscal side, governments helped households and businesses in the form of transfers, furlough payments, wage subsidies and liquidity support. These measures were supplemented with other aspects of social safety nets like unemployment insurance and nutrition assistance. All these actions contributed significantly to lessen the economic impact of COVID-19.',
    },
    {
        id:2,
        title :'Pakistan Economic Review',
        text:'Pakistan economy already had volatile growth pattern over the years, with regular boom and bust cycles facing challenges in achieving long-term and inclusive growth. Unsustainable economic growth was caused by unaddressed long-standing structural issues for example, loss-making State-Owned Enterprises (SOEs), weak external position due to insufficient export capacity and low FDI, under-reformed energy sector, low savings and investment. In the backdrop of these challenges, the present government focused on an economic vision of getting sustainable economic growth through improving efficiency, reducing cost of doing business, improving regulatory environment, enhancing productivity and increasing investment.',
        p1:'Even before the COVID-19 pandemic hit Pakistan’s economy, the government started implementing decisive and far-reaching reforms in every sector of the economy. The reforms started to address the economic imbalances and laid the foundation for improved economic performance in terms of strengthened fiscal and external accounts, exchange rate stability and improved investor’s confidence. Moreover, inflation started to stabilize and market confidence gradually recovered. These reforms paved the way for long-term growth and to end the unsustainable growth pattern that has plagued the economy in the past.',
        p2:'The FY2021 began in the midst of the most severe global health crisis experienced in modern history. Pakistan economy, like rest of the world, has struggled to combat the economic consequences of COVID-19 shock through prompt measures for supporting the economy and saving the lives and livelihoods. Besides, virus containment measures, the government has implemented a comprehensive set of measures including the largest ever economic stimulus package of Rs 1,240 billion, a construction package, an expansion of the social safety net to protect the vulnerable segments of the society and supportive monetary policy stance along with targeted financial initiatives. These measures helped the economy in lessening the negative impact of the pandemic. In contrast to other world economies, Pakistan started witnessing recovery during the first half of FY2021 on the back of continued domestic economic activity due to the above stated measures along with a smart lockdown policy.'
    },
    {
        id:3,
        title:'Growth and Investment',
        text:'The economy of Pakistan rebounded strongly in FY2021 and posted growth of 3.94 percent which is not only substantially higher than the previous two years (-0.47 and 2.08 percent in FY2020 and FY2019 respectively) but also surpassed the target (2.1 percent for FY2021). Despite strict fiscal constraints, timely and appropriate policy measures taken by the government resulted in a V-Shaped economic recovery. The beginning of FY2021 was better in terms of containment of pandemic and economic recovery, however the second wave in late October 2020 and the third wave in March 2021 made government efforts more challenging for containing the pandemic and keeping the economic activities to continue. Regardless of fiscal constraints, relief provision to vulnerable segments and growth support was the government’s utmost Overview of the Economy ix priority. According to the World Bank report on “Social Protection and Jobs Responses to COVID-19: A Real-Time Review of Country Measures” published on May 14, 2021, Pakistan was ranked Fourth in terms of a number of people covered while Third in terms of the percentage of population covered.',
        p1:'Pakistan’s economy is now on course towards strong and sustained recovery. The pandemic resulted in lockdown and depressed demand. Adequate government policies were implemented to keep economy moving. Utilization of unused industrial capacities during the pandemic also helped in economic recovery. On the basis of a rebound in almost all sectors, for FY2021, the provisional GDP growth rate is estimated at 3.9 percent on account of 2.8 percent growth in Agriculture, 3.6 percent in the Industrial sector and 4.4 percent growth in the Services sector. Moreover, GDP at current market prices stood at Rs 47,709 billion, showing a growth of 14.8 percent during FY2021 over last year (Rs 41,556 billion). While in the dollar term, it remained $ 299 billion which is higher than its value recorded last year ($ 263 billion).',
        p2:'Private Consumption has a significantly large share in GDP. This large share implies that Pakistan’s economy is a consumption-driven economy. Better consumer confidence can influence domestic production by increasing demand for durable. Growth in private consumption remained 17 percent in FY2021 as compared to 4 percent last year. On the other hand, growth in Public Consumption remained 11.4 percent, lower than 19.3 percent recorded last year, mainly due to lower growth in interest payments and squeezing of unnecessary expenditures.'
    }
]

export default EconomyData
